services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
    networks: [starter-net]
  starter:
    image: starter
    build: .
    command: ./start.sh
    env_file: [ ./.env ]
    volumes: [ ".:/usr/app/current" ]
    ports: [ "3000:3000" ]
    networks: [ starter-net ]
    links: [ redis ]
    depends_on:
      - redis
volumes:
  redis:
    driver: local
networks:
  starter-net: